#This file describes the network's interfaces on the server
network:
  version: 2
  ethernets:
    enp0s3: # Your network interface name may differ
      dhcp4: no
      addresses: [192.168.56.101/24]
      gateway4: 192.168.56.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
